### ISSUE TITLE
Allow for None to Single/Many Joining

### ISSUE THREAD

**Issue by nsang92** [fordth/jinqJs#1]
Allow for None to Single/Many Joining to be outputted after join.

Say I run the sample code:
```javascript
    var people = [{
        Name: 'Jane',
        Age: 20,
        Location: 'Smithtown'
    }, {
        Name: 'Ken',
        Age: 57,
        Location: 'Islip'
    }, {
        Name: 'Tom',
        Age: 10,
        Location: 'Islip'
    }];

    var population = [{
        Location: 'Islip',
        People: 123
    }, {
        Location: 'Melville',
        People: 332
    }, ];

    var result = jinqJs()
        .from(people)
        .leftJoin(population)
        .on(function(left, right) {
            return (left.Location === right.Location);
        })
        .select();
```

The output is:
```javascript
[{
    "Name": "Jane",
    "Age": 20,
    "Location": "",
    "People": ""
}, {
    "Location": "Islip",
    "People": 123,
    "Name": "Ken",
    "Age": 57
}, {
    "Location": "Islip",
    "People": 123,
    "Name": "Tom",
    "Age": 10
}]
```

However, I expect the output to be a merge of data sets:
```javascript
[{
    "Name": "Jane",
    "Age": 20,
    "Location": "",
    "People": ""
}, {
    "Location": "Islip",
    "People": 123,
    "Name": "Ken",
    "Age": 57
}, {
    "Location": "Islip",
    "People": 123,
    "Name": "Tom",
    "Age": 10
},{
    "Location": "Melville",
    "People": 332,
    "Name": "",
    "Age": ""
}]
```

I have it working with lodash, but the solution is inefficient for large datasets.

**Comment by fordth** [comment]
Hey nsang92, thanks for your feedback. Using the leftJoin is producing an outer join on the collection in the .from() function. So the behavior of the results that you are seeing are expected.  But I do understand your point about a "merge" many join. I will plan to implement that in the next coming version or following one. I will keep you posted. Thanks again :)

**Comment by fordth** [comment]
There is a way to perform a full join and get the results you are looking for until I include a full join in the next version. You can see this Fiddle http://jsfiddle.net/tford/7zr2n4f0/ which has jinqJs performing two outer joins and then a union to get your results.

**Comment by nsang92** [comment]
Hey, thank you! I'll look foward to full join in the next verwion.
