### ISSUE TITLE
Typings deployment

### ISSUE THREAD

**Issue by pascalberger** [fordth/jinqJs#15]
Is there a reason why Typescript typings are deployed in the same NuGet package as the JavaScript library and not through DefinitelyTyped?

Beside that, all DefinitelyTyped typings are installed in `Scripts\typings\<library>\` folder and not in `typings\<library>\`.

For consistency with other libraries I would suggest to use also DefinitelyTyped for deploying the typing definitions and stick to their guidelines.

**Comment by fordth** [comment]
I agree, I did notice that myself but haven't changed the structure. Also I just havent had the time yet to have it moved to DefinitelyTyped repository, but I do plan on getting that done soon.

**Comment by fordth** [comment]
This has been addressed with release version 1.6.1, I will be updating NuGet shortly.. Thank you!
