### ISSUE TITLE
Select where value is 0

### ISSUE THREAD

**Issue by gpminsuk** [fordth/jinqJs#16]
Hi,

In select function this line,
obj[dstFieldName] = (isSimple ? result[index] : (result[index][srcFieldName] || null) );
What is this "|| null" for? It returns null when value is 0.

For example, this query new jinqJs().from([[0],[0],[1],[0],[2]]).select([{field:0,text:0}])
returns [[null],[null],[1],[null],[2]] where expected result is [[0],[0],[1],[0],[2]]

**Comment by fordth** [comment]
Great, catch! I will put that in my next release. Thank you!

**Comment by fordth** [comment]
This has been addressed in release version 1.6.1. Thank you!
