### ISSUE TITLE
Ignore accents when ordering

### ISSUE THREAD

**Issue by ninety7** [fordth/jinqJs#19]
Is it possible to have results ordered ignoring accented letters such as 'á'?

So instead of getting results like:
`["ab", "h", "y", "áa"]`

I want to get them ordered like this:
`["áa", "ab", "h", "y"]`

**Comment by ninety7** [comment]
Here's a solution proposal: #20

**Comment by fordth** [comment]
This has been addressed in release version 1.6.1. Thank you!
