### ISSUE TITLE
website examples

### ISSUE THREAD

**Issue by mg1075** [fordth/jinqJs#2]
Hey, looks like a cool project.

1. On the examples page of the website, under Creating Calculated Columns, `}]);` is on the last line, but I think you want to remove that here because it is an artifact of an angular $scope you have in the real code, and the opening braces are not part of the example.

2. Maybe you could add the jinqJs javascript file to the jinqJs website, so people can play around with the examples in the console?

3. The API doc looks nice; maybe that could be added as html at some point?

Thanks.

**Comment by fordth** [comment]
Thanks mg1075 for the suggestions! I will look into implementing them.

**Comment by fordth** [comment]
I corrected the type on the examples page and added a link to the latest stable version of jinqJs to the web site for use on the console.
