### ISSUE TITLE
Angular modularization

### ISSUE THREAD

**Issue by telno** [fordth/jinqJs#7]
Do you plan to release a version of this which can be injected with Angular's module dependency model?  Similar to what this contributor has done for the *other JS Linq library?  https://github.com/Angular-Public/angular-linq

As I understand it, a huge benefit of Angular is the dependency injection and the cleaning up of the global namespace.

**Comment by fordth** [comment]
Hmm good idea, I will keep the issue open an take a look. Thanks for your suggestion!

**Comment by fordth** [comment]
Added support as a Angular 1.x service as of version 1.5.9
