### ISSUE TITLE
OrderBy has unexpected behaviour

### ISSUE THREAD

**Issue by datenwort** [fordth/jinqJs#8]
Hi,

I tried to use the jinqJs library, but was confused why sorting was not done correctly. It seems that sorting based on string sorting, but if I use a number column for the orderBy criteria it failed.

Here is a [jsfiddle example](https://jsfiddle.net/pt1qevn8/)

**Comment by fordth** [comment]
Yes you are correct, it does a string base sort by default as described here: https://jinqjs.readme.io/docs/orderby 

You can do a number based sort as you are expected too, here is an update to your fiddle:
https://jsfiddle.net/tford/8ue2eg49/

Let me know if you have anymore questions.

Thanks,
Tom

**Comment by datenwort** [comment]
Thx. Have changed the items and now it is running as expected
