### ISSUE TITLE
Aggregate Functions (MAX, MIN) to mimic SQL

### ISSUE THREAD

**Issue by newbie-gk** [fordth/jinqJs#9]
Code below not behaving like it does in SQL; inventory_date_time is created using javascript Date()
In SQL Date/Strings are able to do max/min aggregates
I do see that orderBy() works, maybe the sorting logic there could be applied in finding max/min with the groupBy()
            return new jinqJs()
                .from(springService.localmodelData.inventory)
                .groupBy('company_sku_code', 'inventory_lot_key', 'inventory_uom')
                    .max('inventory_date_time')
                .select()

By the way, is there a pattern that can be used to achieve the results I'm looking for?

**Comment by fordth** [comment]
I created a Plunk example trying to repo your issue: http://plnkr.co/edit/DwTf5E?p=preview 
It seems to be working as expected, feel free to create a working sample and I will check it out.
Thanks.

**Comment by newbie-gk** [comment]
Thank you for the demo :) . I was using a date string like this: http://plnkr.co/edit/P7TGpD2vYqmIuYfYuuKc?p=preview 

I converted my code to date objects like your example and it works fine.
Thanks a lot!

**Comment by fordth** [comment]
No problem, thanks.
